# This routes everything under /latest/ to the current latest version.
# The version number must be changed on each release.
[[redirects]]
  from = "/latest/*"
  to = "/3.0-beta5/:splat"
  status = 301
  force = true

# INSERT NEW VERSION REDIRECT RULES BELOW THIS LINE

# Configure a reverse proxy for published documentation versions. Each
# released documentation version is in a different domain. There is
# one of these sections for each release. Add a new section with the
# latest version number whenever a release has been built. To convert
# a version number to a subdomain, prefix it with a "v" and replace
# dots with dashes.
[[redirects]]
  from = "/3.0-beta5/*"
  to = "https://v3-0-beta5.doc-va-git.xyz/:splat"
  status = 200
  force = true

# This is the default redirect that catches requests whose URL does
# not start with a known version number. They will be redirected to
# the latest docs (which routes to the actual version number).
[[redirects]]
  from = "/*"
  to = "/latest/:splat"
  status = 301
  force = true
